### PR TITLE
Update Rakefile to downcase filenames in coins and index.html

### PR DESCRIPTION
**Pull request by bhdzllr**
This pull request changes the Dash link in index.html, because of case sensitive file systems.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Actually, this file is auto-generated in `./Rakefile` based on the coinmarketcap API, so we'd have to fix the generation of those files instead 👍 

Do you feel comfortable to do that? :)

**Comment by bhdzllr** [comment]
I'm not familiar with Ruby, but if you do not mind, I'd try later. Do you have a suggestion how we could solve that. I looked at the file briefly.

Problem is, symbol and name are equal ("DASH" and "Dash") and links are generate for symbols. But symbol file for Dash ("DASH") never exists because "Dash" is already there.

Maybe try to generate symbol files first or generate links with name.

**Comment by jurvis** [comment]
this looks like it could potentially be an issue for all coins that have the same symbol and coin names 🤔 

@bhdzllr Do correct me if I'm misinterpreting your suggestion, but I doubt generating the files in a different order will change anything since attempting to create `dash-1.txt` and `DASH-1.txt` in `/coins` are identical in the eyes of the filesystem; regardless of order in which they will be created.

The most naive solution I can think of is to have separate folders for symbols and names like that:
image. 

What do you think?

**Comment by bhdzllr** [comment]
You're right. My idea was because the links are generated with the symbols, that these files are generated first and the files with the full name are optional (and of course missing if symbol and name is equal).

Your solution seems more clear.

**Comment by KrauseFx** [comment]
Not sure, but usually I'd say we'd configure the web server to not be case sensitive, right? But in this case, because we use GitHub pages, it might not be possible.

How about, we do it in a simpler way: Let's just have everything lower case?

**Comment by jurvis** [comment]
@KrauseFx I like that — way better 😊 also allows devs to consume these endpoints without having to define two separate string formats

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KrauseFx** [comment]
Alright, let's go for that 👍

**Comment by jurvis** [comment]
@bhdzllr do you want to give this a shot?

**Comment by bhdzllr** [comment]
@jurvis Yes. Thank you. I look at it today.

**Comment by bhdzllr** [comment]
@KrauseFx I have updated the Rakefile, deleted the "coins" folder and executed the Rakefile to get alle coins in lowercase (because I could not figure out how I can overwrite the files with the downcased name in the Rakefile).

My first commit is still in the repo/pull request, how can I remove it?

**Comment by KrauseFx** [comment]
I had to delete and re-add all the coins, since git is not case sensitive, it should be working now :)

**Pull request merged**
